Update jsssr

diff --git a/bin/jsssr b/bin/jsssr
--- a/bin/jsssr
+++ b/bin/jsssr
@@ -1,71 +1,74 @@
 #!/bin/bash
-  
-  progName=$(basename $0)
-  progVersion="1.1"
-  
-  echo "==> ${progName} v${progVersion}"
-  
-  scriptArg="${1}" && readonly scriptArg="${scriptArg}"
-  
-  if [ -z "${scriptArg}" ]; then
-    echo "${progName}: Argument missing" && exit 1
+
+  prog_name=$(basename $0)
+  prog_version="1.1"
+
+  echo "==> ${prog_name} v${prog_version}"
+
+  script_arg="${1}" && readonly script_arg="${script_arg}"
+
+  if [ -z "${script_arg}" ]; then
+    echo "${prog_name}: Argument missing" && exit 1
   fi
-  
-  if [ "$(/usr/bin/curl -sL -w "%{http_code}" "http://google.com/" -o /dev/null)" == "200" ]; then
+
+  if [ "$(curl -sL -w "%{http_code}" "http://google.com/" -o /dev/null)" == "200" ]; then
     online="true"
   else
     online="false"
   fi
-  
+
   if [ -d "/usr/local/jsssr" ]; then
-    libraryExists="true"
-    cDate=$(/usr/bin/stat -f%B "/usr/local/jsssr")
-    thresholdTimestamp=$(/bin/date -j -v -30M +%s)
+    library_exists="true"
+    cdate=$(stat -f%B "/usr/local/jsssr")
+    threshold_timestamp=$(date -j -v -30M +%s)
   else
-    libraryExists="false"
+    library_exists="false"
   fi
-  
-  function updateLibrary() {
-  
-    if [ ${thresholdTimestamp} -gt ${cDate} ] || [ ! -d "/usr/local/jsssr" ]; then
-  
-      tmpFolder=$(getconf DARWIN_USER_TEMP_DIR) && randString=$(/usr/bin/openssl rand -hex 5) && tmpDir="${tmpFolder}${randString}" && /bin/mkdir -p "${tmpDir}"
-  
-      repositoryURI="https://raw.githubusercontent.com/jedetaste/jsssr/master"
-  
+
+  function update_library() {
+
+    if [ ${threshold_timestamp} -gt ${cdate} ] || [ ! -d "/usr/local/jsssr" ]; then
+
+      tmp_folder=$(getconf DARWIN_USER_TEMP_DIR)
+      rand_string=$(openssl rand -hex 5)
+
+      tmp_dir="${tmp_folder}${rand_string}" && mkdir -p "${tmp_dir}"
+
+      repository_uri="https://raw.githubusercontent.com/jedetaste/jsssr/master"
+
       if [ -d "/usr/local/jsssr" ]; then
         rm -rf "/usr/local/jsssr"
-        /bin/mkdir -p "/usr/local/jsssr"
+        mkdir -p "/usr/local/jsssr"
       else
-        /bin/mkdir -p "/usr/local/jsssr"
+        mkdir -p "/usr/local/jsssr"
       fi
-      
+
       echo "==> Pull latest index"
-      /usr/bin/curl -so "${tmpDir}/index" "${repositoryURI}/index"
-      
+      curl -so "${tmp_dir}/index" "${repository_uri}/index"
+
       echo "==> Parse index"
       while read line && [ ! -z "${line}" ]; do
         echo "==> Pull latest '${line}'"
-        linePurged=$(echo "${line}" | sed -e 's/ /%20/g' 2>/dev/null)
-        /usr/bin/curl -so "/usr/local/jsssr/${line}" "${repositoryURI}/Library/${linePurged}"
-        /bin/chmod +x "/usr/local/jsssr/${line}"
-      done < "${tmpDir}/index"
-  
+        line_purged=$(echo "${line}" | sed -e 's/ /%20/g' 2>/dev/null)
+        curl -so "/usr/local/jsssr/${line}" "${repository_uri}/Library/${line_purged}"
+        chmod +x "/usr/local/jsssr/${line}"
+      done < "${tmp_dir}/index"
+
     fi
-  
+
   }
-  
-  if [ "${online}" == "true" ] && [ ${thresholdTimestamp} -gt ${cDate} ]; then
-    updateLibrary
-  elif [ "${online}" == "true" ] && [ "${libraryExists}" == "false" ]; then
-    updateLibrary
+
+  if [ "${online}" == "true" ] && [ ${threshold_timestamp} -gt ${cdate} ]; then
+    update_library
+  elif [ "${online}" == "true" ] && [ "${library_exists}" == "false" ]; then
+    update_library
   else
     echo "==> Libray index is up-to-date"
   fi
-  
-  if [ -s "/usr/local/jsssr/${scriptArg}" ]; then
-    echo "==> Run script '${scriptArg}'"
-    cd "/usr/local/jsssr" && shift && ./"${scriptArg}" "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}"
+
+  if [ -s "/usr/local/jsssr/${script_arg}" ]; then
+    echo "==> Run script '${script_arg}'"
+    cd "/usr/local/jsssr" && shift && ./"${script_arg}" "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}"
   else
-    echo "Error: Script '${scriptArg}' not found" && exit 1
+    echo "Error: Script '${script_arg}' not found" && exit 1
   fi
